global:
  external_labels:
    monitor: codelab-monitor
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
        - "localhost:9090"
  - job_name: redis_exporter
    scrape_interval: 5s
    static_configs:
      - targets:
        - "redis-exporter:9121"
  - job_name: clickhouse-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ["clickhouse-exporter:9116"]